title: [Indirect referencing of images]
description: [How to use a simple trick to mitigate the pain of managing large collections of images in technical documentation.]
plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
remote_theme: pages-themes/midnight@v0.2.0
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md